### ISSUE TITLE
Docs: (Epic) Editorial/style review of plugin-tools website

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#1016]
Review content of plugin-tools for adherence to Grafana style guidelines and fix errors and typos. Ensure that content contains appropriate links to all relevant related pages. Ensure that content is appropriately categorized within the site's hierarchy.

```[tasklist]
### Tasks
- [ ] Review "Get started" for editorial style
- [ ] Review "Key concepts" for editorial style
- [ ] Review "Tutorials" for editorial style
- [ ] Review "How-to guides" for editorial style
- [ ] Review "E2E test" for editorial style
- [ ] Review "Publish a plugin" for editorial style
- [ ] Review "Troubleshooting" for editorial style
- [ ] Review "Reference" for editorial style
```

Question: Who should review these PRs? Do we need to get another member of the doc squad set up to review PRs in this repo?

**Comment by josmperez** [comment]
Per conversation with Fiona, editorial style review will be done "ad hoc" on other PRs rather than in a separate PR.
