### ISSUE TITLE
Docs: (Epic) Technical/correctness review of plugin-tools website (freshness check) 

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#1017]
Review content of plugin-tools for technical accuracy. Ensure that content is up-to-date and contains no technical errors.

Add review-date metadata tag to all topics. Populate this data with best available but imperfect data.

Determine with help of Doc Manager, Dev Manager, and Product Manager an appropriate cadence for freshness checks.

```[tasklist]
### Tasks
- [ ] Review "Get started" for technical accuracy (a.k.a. freshness check).
- [ ] Review "Key concepts" for technical accuracy (a.k.a. freshness check).
- [ ] Review "Tutorials" for technical accuracy (a.k.a. freshness check).
- [ ] Review "How-to guides" for technical accuracy (a.k.a. freshness check).
- [ ] Review "E2E test" for technical accuracy (a.k.a. freshness check).
- [ ] Review "Publish a plugin" for technical accuracy (a.k.a. freshness check).
- [ ] Review "Troubleshooting" for technical accuracy (a.k.a. freshness check).
- [ ] Review "Reference" for technical accuracy (a.k.a. freshness check).
```

Note: These PRs should be reviewed by one or more members of the plugins team. Apart from the PR author, they do not require doc team review.

**Comment by josmperez** [comment]
Discussed in team meeting on 10/7. Will advance conversation in plugin docs meeting on 10/8.

**Comment by josmperez** [comment]
Re-opening for further discussion. @sympatheticmoose @tolzhabayev . In Q3 we talked about doing something like a "documentation day" for reviewing the tech accuracy of the docs. Would you like to select a date for this to occur, or revisit the importance of this issue?
