### ISSUE TITLE
EPIC: `create-plugin update` command improvements

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/plugin-tools#1254]
### Goals

We would like to improve the `create-plugin update` command so it can do more sophisticated updates to the plugins. We are planning to call these tailored and more sophisticated updates **"migrations"**.

**Migrations could:**
- update github workflows
- update specific NPM dependencies, or groups of NPM dependencies
- update and/or add files in the project (not just the ones inside the .config folder)
- update package.json scripts

Another key goal is to make it possible to **reliably test changes to the update command**, something that we are lacking now. As from now on mutating operations can only happen through migration scripts, we will achieve this goal by testing the migration scripts.

### Tasks
- [x] Define the metadata for the migrations (id, description, information on which versions to run it for)
- [x] Create a migration manager to orchestrate the entire update process when the command is run.
- [x] Create a context for the migration manager to perform file system operations. It should provide a way to make it easy
- [x] Adjust log messages so they display the necessary information in an easy-to-read format
- [x] Create a way to test migration scripts
- [x] Add an automated test that checks if the migration scripts are idempotent
- [x] Create a way to share helpers with the migration scripts: the goal is to make it possible for devs writing migrations to perform the most common tasks: updating dependencies, formatting code, running package manager commands, build config files from the handlebars templates.
- [x] Add an eslint rule that forbids migrations from importing `node:fs` to make sure they always use migration manager context

### Ongoing work
The ongoing work is currently available on the [**`updates-as-migrations-pt1`**](https://github.com/grafana/plugin-tools/compare/main...updates-as-migrations-pt1) branch.

If we want we can incrementally roll these things out without changing the current update command behaviour and use an arg of some sort to fine tune before flipping the switch.

Fixes: #820  
Related: 
- #261
- #61

**Comment by leventebalogh** [comment]
I think now we basically have the possibility to all the things that we outlined in the issue (even if only behind a `--experimental-updates` flag for now). Is there any reason to keep this issue still open?
