### ISSUE TITLE
Refactor: Move plugin.json into the root of the project

### ISSUE THREAD

**Issue by mckn** [grafana/plugin-tools#150]
### Package Name

create-plugin

### Description

In the current structure the plugin.json will be generated in the `src` folder where the frontend code lives. This is an inherited legacy from when Grafana only supported frontend plugins. Today Grafana support plugins with both a backend and frontend part where the backend part of the plugin lives in `pkg`.

It would make more sense to move the `plugin.json` from `src/plugin.json` into the root of the project since it relates to both the frontend and the backend part of the plugin.

### Tasks

- [ ] Update the build configuration to support that the plugin.json both lives in the `src` folder and in the root to be backwards compatible.
- [ ] Print a deprecation notice if building a plugin where the plugin.json lives in the `src` folder.
- [ ] Update the template so new plugins will be scaffolded with the plugin.json in the root folder.
- [ ] If you run create-tool update we should probably move the plugin.json from `src` to the root.

**Comment by academo** [comment]
@mckn if you plan to work on this. Make sure to check the https://github.com/grafana/plugin-validator code because it currently assumes the plugin.json is inside `src`

**Comment by mckn** [comment]
> @mckn if you plan to work on this. Make sure to check the https://github.com/grafana/plugin-validator code because it currently assumes the plugin.json is inside `src`

I think it makes sense to do this change since plugin.json belongs to the whole project and not only the frontend code. But as you highlight. There are other places/tooling that expect that the plugin.json is located in the `src` folder. 

Would be nice to get as many of them listed in this issue as possible.

**Comment by jackw** [comment]
If we move the plugin.json out of `src` how do we handle nested plugins?

Moving `plugin.json` out of `src` would require us to reconsider how we recognise a frontend "entry" in the webpack configs. Currently it is one of `module.{ts,tsx,js,jsx}` that lives adjacent to a `plugin.json`. Also the backend build tooling relies on the `plugin.json` to know the name of the compiled executable.

**Comment by mckn** [comment]
> If we move the plugin.json out of `src` how do we handle nested plugins?
> 
> Moving `plugin.json` out of `src` would require us to reconsider how we recognise a frontend "entry" in the webpack configs. Currently it is one of `module.{ts,tsx,js,jsx}` that lives adjacent to a `plugin.json`. Also the backend build tooling relies on the `plugin.json` to know the name of the compiled executable.

Yeah, lots of things to take into consideration but it feels like something we probably should do long term.

**Comment by academo** [comment]
Considering how much work would this bring and how little affects the plugin should we close this issue?

**Comment by mckn** [comment]
I'm not sure about that. We will "soon" have big changes of the structure of the plugins when the app platform work is introduced. So I guess it would be good to introduce this change as part of that work (if the plugin.json still exists in that scenario).
