### ISSUE TITLE
Epic: Documentation improvements

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#171]
This repository makes use of [Docusaurus and GH pages for documentation](https://grafana.github.io/plugin-tools/) however the documentation could do with some improvements:

- [x] Add docker documentation explaining how to make use of the development env.
- [x] Add CI (GH workflows) documentation explaining what is included and how to make use of it
- [x] Distributing your plugin should explain the process for first time community submissions
- [ ] Add Testing (unit and e2e) documentation for backend / frontend
- [ ] Maybe add editor setup documentation?

**Comment by jackw** [comment]
Given the ongoing developer portal work I'm closing this as it's not really relevant now.
