### ISSUE TITLE
[meta] Cypress 12 migration

### ISSUE THREAD

**Issue by academo** [grafana/plugin-tools#299]
This a meta issue to track progress of the migration to cypress 12.

```[tasklist]
### Migration path to cypress 12
- [ ] Merge https://github.com/grafana/grafana/pull/60117 for Grafana 10.1.x
- [ ] Write migration guide to upgrade from grafana/e2e <=10.0.x  to 10.1.x
- [ ] Update create-tool to detect and correctly ask to update the cypress configuration if grafana/e2e 10.1.x is detected and an old cypress configuration is detected.
- [ ] Update create-tool to generate plugins using grafana >=10.1.x and include the cypress 12 configuration
```

**Comment by jackw** [comment]
This issue has been superseded by the plugin-e2e work.
