### ISSUE TITLE
EPIC: migrate plugins to use Cloud Access Policies

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#316]
API keys are being deprecated in favour of Access Policies: https://grafana.com/docs/grafana-cloud/account-management/authentication-and-permissions/access-policies/.

Currently we advise and require the use of API keys to sign plugins, so we need to figure out the impact of this change and start moving developers to use the new mechanism.

```[tasklist]
### Tasks
- [x] 🤞 try a Access Policy token and see if everything still works with no further changes...
- [x] Validate the required access [scope(s)](https://github.com/grafana/auth/blob/main/pkg/api/models/scope.go) for replacing an API key token
- [x] If changes are required in `sign-plugin`, determine whether we can support both until API keys are fully removed
- [ ] https://github.com/grafana/plugin-tools/issues/323
- [ ] https://github.com/grafana/plugin-tools/issues/324
- [ ] https://github.com/grafana/plugin-tools/issues/328
- [ ] https://github.com/grafana/plugin-tools/issues/329
- [ ] https://github.com/grafana/plugin-tools/issues/330
```

**Comment by tolzhabayev** [comment]
Tried it out

`plugins:write` is the scope that has to be used.

**Comment by tolzhabayev** [comment]
No changes are required to sign plugin:

This "If changes are required in `sign-plugin`, determine whether we can support both until API keys are fully removed" can be removed / checked as done.
