### ISSUE TITLE
Epic: Enhance examples documentation

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#429]
```[tasklist]
### Tasks
- [ ] [Add a draft title or issue reference here](https://github.com/grafana/grafana/issues/69968)
- [x] Consider adding an Examples section to plugin-docs
- [ ] Edit content of examples for Grafana style
- [ ] Restructure examples into a consistent format
```

**Comment by mckn** [comment]
I'm moving it back to in progress, is that ok with you @josmperez?

**Comment by josmperez** [comment]
@mckn Yes, this is an active issue, thanks for reopening it.
