### ISSUE TITLE
Feat: Migrate packages to ESM

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#654]
### Which areas does this feature request relate to

- [X] Create Plugin
- [X] Sign Plugin
- [ ] Documentation

### Problem

We have dependencies in our projects in this repo which we cannot update to because they are ESM only packages and current build tooling doesn't support them.

### Solution

Migrate sign-plugin and create-plugin to build as ESM packages. We only support node LTS and as they are cli scripts that are run via NPX I don't consider this will be a breaking change if we drop CommonJS support.

```[tasklist]
### Tasks
- [x] Migrate create-plugin to ESM only package https://github.com/grafana/plugin-tools/pull/658
- [x] Migrate sign-plugin to ESM only package https://github.com/grafana/plugin-tools/pull/662
- [x] Clean up mono-repo post ESM only package changes https://github.com/grafana/plugin-tools/pull/694
```

### Alternatives

Don't update dependencies?

### Are you interested in contributing the solution?

- [X] Yes
- [ ] No

**Comment by jackw** [comment]
Closing as all related work is now merged to main.
