### ISSUE TITLE
Feat: Add proper selectors for UI components

### ISSUE THREAD

**Issue by sunker** [grafana/plugin-tools#724]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [X] Plugin E2E
- [ ] Documentation

### Problem

In some places in the code when plugin-e2e needs to interact with the Grafana UI, propers e2e-selectors are missing so adhoc selector are being used. See this example:
```typescript
await this.ctx.page.getByRole('button', { name: 'TEST' }).click();
```

This is brittle and error prone. We should always use selectors defined in grafana/e2e-selectors rather than using adhoc selectors like this.

### Solution

1. Add new selectors to grafana/e2e-selectors
2. Make sure they're being used in grafana/ui
3. Update versioned selectors in grafana/plugin-e2e accordingly and make sure they're used throughout the plugin-e2e codebase

The following interactions need proper selectors:

```[tasklist]
### Tasks
- [ ] [run query in annotation edit page](https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts#L34)
- [ ] [add new annotation in annotation list page](https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/pages/AnnotationPage.ts#L39)
- [ ] [set panel title in panel edit page](https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/pages/PanelEditPage.ts#L73) 
- [ ] [set time zone in time zone picker](https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/components/TimeRange.ts#L22) 
```

**Comment by tolzhabayev** [comment]
@sunker can we turn the "The following interactions need proper selectors" into a tasklist and change the URLs so that they are working again e.g.
https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/dist/models/AnnotationEditPage.js -> https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts

**Comment by sunker** [comment]
> @sunker can we turn the "The following interactions need proper selectors" into a tasklist and change the URLs so that they are working again e.g. https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/dist/models/AnnotationEditPage.js ->
> 
> https://github.com/grafana/plugin-tools/blob/dba30f60c880de9778c66bb32957257441b33a35/packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts#L34

Yep done!
