### ISSUE TITLE
Plugin-E2E: Docs

### ISSUE THREAD

**Issue by sunker** [grafana/plugin-tools#731]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [X] Plugin E2E
- [ ] Documentation

### Problem

Grafana Plugin E2E needs documentation. 

### Solution

Proposed structure: 

```bash
├── introduction.md 
├── getting-started.md # installation, writing tests and setup basic CI workflow
├── locating-elements.md
├── feature-toggles.md
├── authentication.md
├── ci.md
├── setup-resources.md
├── how-to-test-data-source-plugins.md # frontend and backend
│   ├── configuration-editor.md
│   ├── query-editor.md
│   ├── panel-data-assertion.md
│   ├── custom-variable-editor.md
│   ├── template-variable-interpolation.md
│   ├── annotation-editor.md
├── how-to-test-panel-plugins.md
├── how-to-test-app-plugins.md
├── api ref # low priority, and only if we can auto-generate it from tsdoc
│   ├── assertions.md
│   ├── classes.md
│   └── fixtures.md
```

### Are you interested in contributing the solution?

- [X] Yes
- [ ] No
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/plugin-tools/pull/701
- [ ] https://github.com/grafana/plugin-tools/pull/723
- [x] authentication-and-rbac
- [x] ci
- [x] provisioning
- [x] how-to-test-data-source-plugins
- [x] how-to-test-panel-plugins
- [x] how-to-test-app-plugins https://github.com/grafana/plugin-tools/pull/891
- [x] playwright-configuration
- [x] migrating-from-grafana-e2e
```

**Comment by sunker** [comment]
After discussions with Jack and Esteban, it became clear auto-generating api ref based on tsdocs costs more than it gives. So I decided to add a [Use the API](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/api) article instead. 

Don't see a strong need for adding a `Best practices` guide right now, so removing it from the task list. 

All other articles have been published, so I'm closing this issue.
