### ISSUE TITLE
Monorepo: Follow up tasks

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#74]
Once #72 in merged we need to address the following things:

- [x] Define what to do with version parameter of [ManifestInfo](https://github.com/grafana/create-plugin/pull/72/files#diff-e4729107c017626b3b1d757d6e150c786eb52ee6cb9b26a6d7593a64378a9071R18-R20) and adjust the code accordingly #82 
- [x] Rename repo to `grafana/plugin-tools`
- [x] Change the references in this PR's readme and other files from `create-plugin` to `plugin-tools` #83 
- [x] #118
- [x] Improve sign-plugin documentation #83

**Comment by jackw** [comment]
Closing this as tasks are complete.
