### ISSUE TITLE
Create Plugin: Update github workflows to use shared actions

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#742]
This is to address inconsistency in our CI and Release workflows so we just have to maintain build-action as well as some security improvements (getting flagged by tooling)
```[tasklist]
### Tasks
- [x] Update [release.yaml](https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/github/workflows/release.yml) to use https://github.com/grafana/plugin-actions/blob/main/build-plugin/action.yml
- [x] Update [build-action](https://github.com/grafana/plugin-actions/blob/main/build-plugin/action.yml) versions i.e. setup-node -> v4
- [x] Add top level `permissions: read-all` and job level `permissions: contents: write` as appropriate
- [ ] Update ci.yaml to use plugin-actions
```

**Comment by sympatheticmoose** [comment]
Created some quick PRs which cover everything except consolidation.

**Comment by sympatheticmoose** [comment]
@jackw https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/github/workflows/ci.yml still seems to not use it?

**Comment by jackw** [comment]
Have added it to the task list. 👍 

Not sure how best to handle adding plugin-actions to ci.yml. Probably needs splitting up cos it has dependencies on [other scaffolded workflows](https://github.com/grafana/plugin-tools/pull/1357/files#diff-97f3aa13af615c55d3d9151ff85d191d5e228ba2a99a070ad0a6f316b54a85c7).
