### ISSUE TITLE
EPIC: Create Plugin DX Improvements in debugging and reloading areas

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/plugin-tools#814]
**Why?**
We want to improve the default workflow by providing a way to better debug the backend components and enable reloading of backend components.

**Tasks**

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/plugin-tools/issues/737
- [ ] https://github.com/grafana/plugin-tools/issues/735
- [ ] https://github.com/grafana/plugin-tools/issues/338
- [ ] https://github.com/grafana/plugin-tools/issues/1058
```

**How do we know we were successful?**
- The "How to use it" docs are updated and published
- Showcase in office hours
- Collect feedback on what is missing with regards to debugging and local reloading

**Comment by simonbuehler** [comment]
hi 👋 

is this already available or documented? getting into devel of a backend plugin and this would be handy to use
