### ISSUE TITLE
Epic: Reorganize 'plugin-tools' site to match current site structure plan

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#875]
This epic covers for the entire site of plugin-tools:

- Reorganize 'plugin-tools' site to match the current site structure plan
- Create redirects from old location of files so that nothing breaks
- Update links within plugin-tools itself so that they go to the new file locations
- Fix any typos or minor style issues that may be noticed during this process.
```[tasklist]
### Tasks
- [x] Chunk 1: Reference directory
- [x] Chunk 2: Introduction/Key Concepts directories
- [x] Chunk 3: Create a Plugin directories
- [x] Chunk 4: Other directories
```

**Comment by josmperez** [comment]
Reorg complete.
