### ISSUE TITLE
Reorganize plugin-tools site based on new design plan

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#925]
Fix problems with less than ideal plugin-tools organization. Incorporate feedback received in Q1 from many stakeholders, external and internal to the plugins team and approved in a design plan.

This process includes the following:
- Move or rename folders and files
- Fix broken links on site caused by move/renames
- Fix broken links on other sites, principally grafana/grafana and plugin-examples
- Create new topic placeholders for new topics, make edits and/or assign to developers to make edits
- Test all changes through build process on Docker site and dev site
```[tasklist]
### Tasks
- [x] Reorganize 'reference' section
- [x] Reorganize 'introduction' section
- [ ] Reorganize 'create-a-plugin/develop-a-plugin' section
- [ ] Reorganize 'create-a-plugin/extend-a-plugin' section
```
